#!/usr/bin/env bash
#good a rat

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
sudo service haproxy start
echo "frontend haproxynode
        bind *:80
	mode http
	default_backend backendnodes
backend backendnodes
 	balance roundrobin
	server 943-web-01 35.237.238.105:80 check
	server 943-web-02 34.74.131.167:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart