#!/usr/bin/env bash
#Prints Holberton School 10 times
i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 8 ]
    then
	echo -e 'Holberton School\nHi'
    else
	echo "Holberton School"
    fi
    let i=i+1
done
