#!/usr/bin/env bash
#Prints Holberton School 10 times
i=1
while [ $i -lt 21 ]
do
    case $i in
	4)
	    echo -e $i'\nbad luck from China'
	    ;;
	9)
	    echo -e $i'\nbad luck from Japan'
	    ;;
	17)
	    echo -e $i'\nbad luck from Italy'
	    ;;
	*)
	    echo $i
	    ;;
    esac
    let i=i+1
done
